### ISSUE TITLE
no category added

### ISSUE THREAD

**Issue by djalexz** [Prinz23/nzbgetpp#6]
Hi,

the category is not added to the nzb files if i import a zipped file with multiple nzb files.

Thank you

**Comment by Prinz23** [comment]
I tested and for me both with python 2.7 and python 3.10 the category is added. 

Maybe check and delete in nzbget `TempDir` (see nzbget settings page: `PATHS`) directory the subdir/files: `nzbget\unzip_scan\info`   . It could be that the file is corrupted and therefor not loaded/saved correctly.

**Comment by djalexz** [comment]
Hi,
and thank you for you response.
Unfortunately, this does not fix the error either.

If I add multiple nzb files and select the category, then everything works.

As soon as I add a ZIP or RAR file with several nzb files as content, the category is no longer transferred to nzbget.

**Comment by Prinz23** [comment]
Are you sure that unzip.py is even executed for the zip you add? 

Please check if you enabled globally and in the category specific settings that unzip is selected.

Nzbget settings: 

- `EXTENSION SCRIPTS` -> `Extensions` 
- `CATEGORIES` for each category the setting: `CategoryX.Extensions` (X = a number of the category)

if you don't enable the script globally or for the category the settings (like category, pause, ...) aren't set for the containing nzb's

**Comment by djalexz** [comment]
Oh perfect.
thank you very much.
unzip.py was really not active under `EXTENSION SCRIPTS` -> `Extensions`.
